### ISSUE TITLE
CMAKE Build - libogg not found

### ISSUE THREAD

**Issue by Glog78** [xoreos/xoreos#107]
The cmake file doesn't seem to find libogg even it is clearly installed in my system.

[only_config.txt](https://github.com/xoreos/xoreos/files/46669/only_config.txt)

[******@archbox build-clang]$ ls -al /usr/lib/libogg*
lrwxrwxrwx 1 root root    19 13. Sep 2014  /usr/lib/liboggkate.so -> liboggkate.so.1.2.2
lrwxrwxrwx 1 root root    19 13. Sep 2014  /usr/lib/liboggkate.so.1 -> liboggkate.so.1.2.2
-rwxr-xr-x 1 root root 10216 13. Sep 2014  /usr/lib/liboggkate.so.1.2.2
lrwxrwxrwx 1 root root    15 13. Okt 2014  /usr/lib/libogg.so -> libogg.so.0.8.2
lrwxrwxrwx 1 root root    15 13. Okt 2014  /usr/lib/libogg.so.0 -> libogg.so.0.8.2
-rwxr-xr-x 1 root root 26840 13. Okt 2014  /usr/lib/libogg.so.0.8.2

[******@archbox build-clang]$ ls -al /usr/lib64/libogg*
lrwxrwxrwx 1 root root    19 13. Sep 2014  /usr/lib64/liboggkate.so -> liboggkate.so.1.2.2
lrwxrwxrwx 1 root root    19 13. Sep 2014  /usr/lib64/liboggkate.so.1 -> liboggkate.so.1.2.2
-rwxr-xr-x 1 root root 10216 13. Sep 2014  /usr/lib64/liboggkate.so.1.2.2
lrwxrwxrwx 1 root root    15 13. Okt 2014  /usr/lib64/libogg.so -> libogg.so.0.8.2
lrwxrwxrwx 1 root root    15 13. Okt 2014  /usr/lib64/libogg.so.0 -> libogg.so.0.8.2
-rwxr-xr-x 1 root root 26840 13. Okt 2014  /usr/lib64/libogg.so.0.8.2

[*****@archbox build-clang]$ ls -al /usr/lib32/libogg*
lrwxrwxrwx 1 root root    15 20. Okt 2014  /usr/lib32/libogg.so -> libogg.so.0.8.2
lrwxrwxrwx 1 root root    15 20. Okt 2014  /usr/lib32/libogg.so.0 -> libogg.so.0.8.2
-rwxr-xr-x 1 root root 26044 20. Okt 2014  /usr/lib32/libogg.so.0.8.2

System OS: Arch current

**Comment by DrMcCoy** [comment]
I can reproduce that on both my Arch Linux laptop and my Debian Sid desktop machine. xoreos still compiles and links for me, though.

Interestingly, when I change "libogg" to "ogg" in the find_library() call in [cmake/FindOgg.cmake:14](https://github.com/xoreos/xoreos/blob/master/cmake/FindOgg.cmake#L14), it find the library for me. FindMad.cmake and FindVorbis.cmake also don't prefix "lib" there.

@berenm, could you take a look? Was there a reason for "libogg" I'm missing here, or is it a typo? Do some distributions need it to be "libogg"? What about the WIN32 case in line 10? Thanks!
