### ISSUE TITLE
Failure to link on OpenBSD

### ISSUE THREAD

**Issue by bentley** [xoreos/xoreos#109]
xoreos-0.0.3 builds mostly successfully but fails at link time on OpenBSD.

I get the same results with GCC 4.2 and 4.9, and with both BSD make and GNU make.

(Note: xoreos-tools builds and runs fine.)

    /usr/bin/libtool  --tag=CXX    --mode=link c++ -I.. -ggdb  -Wall -Wpointer-arith -Wshadow -Wsign-compare -Wunused-parameter   -DGLEW_STATIC -DGLEW_NO_GLU -Wnon-virtual-dtor -Wno-overloaded-virtual -DUNIX    -I/usr/local/include/libxml2 -I/usr/local/include  -I/usr/local/include -I/usr/local/include/SDL2 -I/usr/X11R6/include -D_REENTRANT -I/usr/X11R6/include -I/usr/X11R6/include -pthread -I/usr/X11R6/include/freetype2           -O2 -pipe  -L/usr/local/lib -L/usr/X11R6/lib -o xoreos cline.o xoreos.o    engines/libengines.la  events/libevents.la  video/libvideo.la  sound/libsound.la  graphics/libgraphics.la  aurora/libaurora.la  common/libcommon.la  ../lua/liblua.la   -liconv -lz -llzma  -L/usr/local/lib -lxml2 -lz -L/usr/local/lib -liconv -lm  -L/usr/local/lib -lSDL2 -pthread -L/usr/X11R6/lib -R/usr/X11R6/lib -lGL  -L/usr/X11R6/lib -lfreetype -lz -lxvidcore  -lopenal -lfaad -lmad -logg  -lvorbisfile   -lboost_system-mt   -lboost_filesystem-mt   -lboost_regex-mt   -lboost_atomic-mt   -lboost_locale-mt   
    libtool: link: c++ -o xoreos -pthread -I.. -ggdb -Wall -Wpointer-arith -Wshadow -Wsign-compare -Wunused-parameter -DGLEW_STATIC -DGLEW_NO_GLU -Wnon-virtual-dtor -Wno-overloaded-virtual -DUNIX -I/usr/local/include/libxml2 -I/usr/local/include -I/usr/local/include -I/usr/local/include/SDL2 -I/usr/X11R6/include -D_REENTRANT -I/usr/X11R6/include -I/usr/X11R6/include -I/usr/X11R6/include/freetype2 -O2 -pipe cline.o xoreos.o /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/engines/.libs/libengines.a /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/events/.libs/libevents.a /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/video/.libs/libvideo.a /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/sound/.libs/libsound.a /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/graphics/.libs/libgraphics.a /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/aurora/.libs/libaurora.a /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/common/.libs/libcommon.a /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/lua/.libs/liblua.a -L.libs -liconv -lz -llzma -lxml2 -lm -lSDL2 -lsndio -lusbhid -lGL -lexpat -lglapi -lpthread -lXdamage -lXfixes -lX11 -lxcb -lX11-xcb -lxcb-glx -lxcb-dri2 -lXxf86vm -lXext -ldrm -lfreetype -lxvidcore -lopenal -lfaad -lmad -logg -lvorbisfile -lvorbis -lboost_system-mt -lstdc++ -lboost_filesystem-mt -lboost_regex-mt -lboost_atomic-mt -lboost_locale-mt -Wl,-rpath,/usr/X11R6/lib,-rpath-link,/usr/local/lib,-rpath-link,/usr/X11R6/lib
    .libs/libxml2.so.15.1: warning: warning: strcpy() is almost always misused, please use strlcpy()
    .libs/libGL.so.16.0: warning: warning: random() may return deterministic values, is that what you want?
    .libs/libxvidcore.so.4.4: warning: warning: vsprintf() is often misused, please use vsnprintf()
    .libs/libboost_regex-mt.so.6.0: warning: warning: wcscpy() is almost always misused, please use wcslcpy()
    /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/engines/.libs/libengines.a(functions.o): In function `Engines::KotOR2::Functions::getRandom(int, int, int)':
    script/functions.cpp:106: warning: warning: rand() may return deterministic values, is that what you want?
    .libs/libxml2.so.15.1: warning: warning: strcat() is almost always misused, please use strlcat()
    /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/common/.libs/libcommon.a(pe_exe.o): In function `Common::PEResourceID::toString() const':
    /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/common/pe_exe.cpp:96: warning: warning: sprintf() is often misused, please use snprintf()
    /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/engines/.libs/libengines.a(nwn.o): In function `Engines::NWN::NWNEngine::deinit()':
    /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/engines/nwn/nwn.cpp:468: undefined reference to `Engines::NWN::Game::~Game()'
    /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/engines/.libs/libengines.a(nwn.o): In function `~NWNEngine':
    /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/engines/nwn/nwn.cpp:68: undefined reference to `Engines::NWN::Game::~Game()'
    /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/engines/nwn/nwn.cpp:68: undefined reference to `Engines::NWN::Game::~Game()'
    /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/engines/nwn/nwn.cpp:68: undefined reference to `Engines::NWN::Game::~Game()'
    /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/engines/.libs/libengines.a(nwn.o): In function `Engines::NWN::NWNEngine::run()':
    /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/engines/nwn/nwn.cpp:132: undefined reference to `Engines::NWN::Game::Game(Engines::NWN::NWNEngine&, Engines::Console&, Engines::NWN::Version const&)'
    /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/engines/nwn/nwn.cpp:133: undefined reference to `Engines::NWN::Game::run()'
    /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/engines/.libs/libengines.a(console.o): In function `Engines::NWN::Console::cmdExitModule(Engines::Console::CommandLine const&)':
    /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/engines/nwn/console.cpp:178: undefined reference to `Engines::NWN::Game::getModule()'
    /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/engines/.libs/libengines.a(console.o): In function `Engines::NWN::Console::updateAreas()':
    /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/engines/nwn/console.cpp:153: undefined reference to `Engines::NWN::Game::getModule()'
    /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/engines/.libs/libengines.a(console.o): In function `Engines::NWN::Console::cmdListAreas(Engines::Console::CommandLine const&)':
    /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/engines/nwn/console.cpp:231: undefined reference to `Engines::NWN::Game::getModule()'
    /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/engines/.libs/libengines.a(console.o): In function `Engines::NWN::Console::updateModules()':
    /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/engines/nwn/console.cpp:147: undefined reference to `Engines::NWN::Game::getModules(std::vector<Common::UString, std::allocator<Common::UString> >&)'
    /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/engines/.libs/libengines.a(console.o): In function `Engines::NWN::Console::cmdLoadCampaign(Engines::Console::CommandLine const&)':
    /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/engines/nwn/console.cpp:202: undefined reference to `Engines::NWN::Game::getModule()'
    /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/engines/.libs/libengines.a(console.o): In function `Engines::NWN::Console::cmdLoadModule(Engines::Console::CommandLine const&)':
    /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/engines/nwn/console.cpp:220: undefined reference to `Engines::NWN::Game::getModule()'
    /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/engines/.libs/libengines.a(console.o): In function `Engines::NWN::Console::cmdGotoArea(Engines::Console::CommandLine const&)':
    /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/engines/nwn/console.cpp:242: undefined reference to `Engines::NWN::Game::getModule()'
    /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/engines/.libs/libengines.a(console.o): In function `Engines::NWN::Console::cmdPlayMusic(Engines::Console::CommandLine const&)':
    /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/engines/nwn/console.cpp:265: undefined reference to `Engines::NWN::Game::playMusic(Common::UString const&)'
    /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/engines/.libs/libengines.a(console.o): In function `Engines::NWN::Console::cmdStopMusic(Engines::Console::CommandLine const&)':
    /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/engines/nwn/console.cpp:261: undefined reference to `Engines::NWN::Game::stopMusic()'
    collect2: ld returned 1 exit status
    Error while executing c++ -o xoreos -pthread -I.. -ggdb -Wall -Wpointer-arith -Wshadow -Wsign-compare -Wunused-parameter -DGLEW_STATIC -DGLEW_NO_GLU -Wnon-virtual-dtor -Wno-overloaded-virtual -DUNIX -I/usr/local/include/libxml2 -I/usr/local/include -I/usr/local/include -I/usr/local/include/SDL2 -I/usr/X11R6/include -D_REENTRANT -I/usr/X11R6/include -I/usr/X11R6/include -I/usr/X11R6/include/freetype2 -O2 -pipe cline.o xoreos.o /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/engines/.libs/libengines.a /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/events/.libs/libevents.a /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/video/.libs/libvideo.a /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/sound/.libs/libsound.a /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/graphics/.libs/libgraphics.a /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/aurora/.libs/libaurora.a /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/src/common/.libs/libcommon.a /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3/lua/.libs/liblua.a -L.libs -liconv -lz -llzma -lxml2 -lm -lSDL2 -lsndio -lusbhid -lGL -lexpat -lglapi -lpthread -lXdamage -lXfixes -lX11 -lxcb -lX11-xcb -lxcb-glx -lxcb-dri2 -lXxf86vm -lXext -ldrm -lfreetype -lxvidcore -lopenal -lfaad -lmad -logg -lvorbisfile -lvorbis -lboost_system-mt -lstdc++ -lboost_filesystem-mt -lboost_regex-mt -lboost_atomic-mt -lboost_locale-mt -Wl,-rpath,/usr/X11R6/lib,-rpath-link,/usr/local/lib,-rpath-link,/usr/X11R6/lib
    *** Error 2 in src (Makefile:605 'xoreos')
    *** Error 1 in src (Makefile:679 'all-recursive')
    *** Error 1 in . (Makefile:674 'all-recursive')
    *** Error 1 in /usr/ports/pobj/xoreos-0.0.3/xoreos-0.0.3 (Makefile:519 'all')

**Comment by DrMcCoy** [comment]
Aw, rats. :(

I need to look at that more closely tomorrow. Can you give me a log of a full, clean (but still verbose) compile (especially the linking stage of libengines.a)?

Funny that it only can't find NWN stuff.

That's with the autotools, I presume? Can you see if it works with CMake? If so, can you see a difference in how the compiler/linker is called?

Does changing the linking order of the convenience libraries, either during libengines.a or xoreos itself change anything?

Is the that the v0.0.3 tag or the current master? Does the other one work? Or did it work with, say, v0.0.2 or earlier?

**Comment by bentley** [comment]
This is xoreos-0.0.3 from the source tarball on the releases page, using the pre‐generated configure script. I haven’t tested earlier versions.

Full build log: [xoreos-0.0.3-failure.txt](https://github.com/xoreos/xoreos/files/51618/xoreos-0.0.3-failure.txt)

The CMake build doesn’t seem to work either, but it fails much earlier, during the configure stage (it can’t find either libmad or OggConfig.cmake; I haven’t looked into the cause).

**Comment by DrMcCoy** [comment]
> it can’t find either libmad or OggConfig.cmake

That might have been fixed with https://github.com/xoreos/xoreos/commit/1acc91d23872fc9517ab2e93750a87a40bdf46a7 . Maybe.

**Comment by bentley** [comment]
Testing against git master, both the autoconf (no extra steps necessary) and CMake (needs to pass SDL2_INCLUDE_DIR and SDL2_LIBRARY) builds work on OpenBSD. So I guess this can be closed. But a new release tarball might be nice for packaging purposes :)

**Comment by DrMcCoy** [comment]
Interesting. Well, good that it works, now. :)

Still, I don't really see a difference that would matter in the diff between v0.0.3 and master (I'm probably missing something), so I'm a bit confused on how this happened and how it got fixed. :/
I'd really like to understand what's going on here.

I know it's time-intense, especially since it involves compiling xoreos over and over, but could you maybe do a git bisect to find out where exactly it got fixed? Oh, and also, if git v0.0.3 is also broken, because maybe I messed up packaging somehow? Thanks!

If that's too much work for you, I understand. Then I'll see if I can set up an OpenBSD VM and try for myself. I know nothing about OpenBSD, so it might also take some time.
