### ISSUE TITLE
NWN: Crash in the animation code

### ISSUE THREAD

**Issue by DrMcCoy** [xoreos/xoreos#189]
Due to the changes in 1f84589e9, NWN now crashes when entering a module.

The crash is at src/graphics/aurora/animation.cpp:79 in `Graphics::Aurora::Animation::update()`, `model->_animNodeMap.size()` is 0, but it still tries to go into it with `operator[]()` (parameter: `animNode->_nodeNumber` == 0).

**Comment by DrMcCoy** [comment]
@seedhartha, if you have some time to debug this (if you have NWN, that is), that would be great. :)

**Comment by seedhartha** [comment]
Sure, I'll take a look.

**Comment by seedhartha** [comment]
Check out #190.

**Comment by DrMcCoy** [comment]
Merged as cc0cf9be2bcc1ae67c39ab42ea169789c423afd0,  thanks! :)
