### ISSUE TITLE
The Witcher: Environment loads but nothing else does

### ISSUE THREAD

**Issue by RiderExMachina** [xoreos/xoreos#205]
When loading The Witcher, the environment loads, but it is missing shaders and characters. The player takes control of a camera, which can go anywhere, but can otherwise do nothing else. 

I'd like to provide more information, but the above is the only thing I know for 100% certain.

**Comment by DrMcCoy** [comment]
Yes, that's the current state of The Witcher in xoreos. Nothing else has been implemented yet. I'm closing this issue, since it's not technically a bug per se.

You are, of course, welcome to work on The Witcher in xoreos, if you are able and willing :)

**Comment by RiderExMachina** [comment]
>You are, of course, welcome to work on The Witcher in xoreos, if you are able and willing
I'd love to work more on xoreos, though I'd rather work more on KOTOR, because similar issues occur there. ;)

That said, I don't think you should close this, as even though it's not a bug, it's a feature that should be worked on, and it tells other people the progress of The Witcher if they look through the issues page (which is helpful because the latest updated on your website is from November 2016).
