### ISSUE TITLE
KOTOR: Flying Droids

### ISSUE THREAD

**Issue by Nostritius** [xoreos/xoreos#268]
It seems the the droids on the endar spire are flying around.
![bildschirmfoto zu 2018-05-27 18-12-21](https://user-images.githubusercontent.com/17826813/40588167-c147750c-61d9-11e8-80a7-b6be0b4ead6b.png)
![bildschirmfoto zu 2018-05-27 18-13-44](https://user-images.githubusercontent.com/17826813/40588168-c168b5dc-61d9-11e8-808f-7a141a812884.png)

**Comment by seedhartha** [comment]
Fixed by #291.

**Comment by Nostritius** [comment]
This seems to be fixed.
