### ISSUE TITLE
KOTOR: Seg Faults on loading map

### ISSUE THREAD

**Issue by RiderExMachina** [xoreos/xoreos#284]
Loading from a save results in 

> WARNING: No such GUI element "LBL_MAPVIEW"!
[1]    6276 segmentation fault (core dumped)  ./xoreos kotor

and creating a new game results in

> WARNING: Failed to create texture "M01aa_04a_a0002t" (-1)
    Because: No such image resource "M01aa_04a_a0002t"
WARNING: Failed to create texture "DOR_LHR02_a00004" (-1)
    Because: No such image resource "DOR_LHR02_a00004"
WARNING: Failed to create texture "DOR_LHR02_a00004" (-1)
    Because: No such image resource "DOR_LHR02_a00004"
WARNING: Failed to create texture "DOR_LHR02_a00004" (-1)
    Because: No such image resource "DOR_LHR02_a00004"
WARNING: Failed to create texture "DOR_LHR02_a00004" (-1)
    Because: No such image resource "DOR_LHR02_a00004"
WARNING: No such GUI element "LBL_MAPVIEW"!
[1]    7181 segmentation fault (core dumped)  ./xoreos kotor

I'm running build e231bcd, so I suspect a rogue function.

**Comment by seedhartha** [comment]
I'm unable to reproduce the issue. Could you run the game with valgrind and attach the logs here?

**Comment by DrMcCoy** [comment]
Since map view isn't there, that could be another case of not properly allowing for missing GUI elements when running on a non-standard resolution? @seedhartha, try setting `--width` and `--height` to weird values, see if the problem shows.

**Comment by seedhartha** [comment]
True, the game segfaults at resolution 1366x768.

**Comment by DrMcCoy** [comment]
Should be fixed with 6b6954f88c7c3c61fad9d514e633b3feb34ed9f3 :)

**Comment by RiderExMachina** [comment]
Yep, this did fix the Seg Fault issue.
