### ISSUE TITLE
AURORA: ERF V2.1

### ISSUE THREAD

**Issue by Nostritius** [xoreos/xoreos#334]
The xbox version of DragonAge: Origins uses another yet unknown version of ERF, namely 2.1 which cannot be read by the current ERFFile class.

**Comment by DrMcCoy** [comment]
Ah, I was wondering why there's V2.0 and V2.2. :P

**Comment by DrMcCoy** [comment]
Implemented with 84d1c78afed24aa5eaec1da48e02be85f44aaf73 :P
