### ISSUE TITLE
AURORA: ERF Compression 2 and 3

### ISSUE THREAD

**Issue by Nostritius** [xoreos/xoreos#335]
The xbox version of Dragon Age 2 uses two new compressions with the ids 2 and 3 in the erf files which cannot be recognized from ther ERFFile class at the moment.

**Comment by Nostritius** [comment]
My suspicion is, that it is lzo since bioware used this compression before Dragon Age 2 in the Mass Effect 2 pcc archives.

**Comment by logzero** [comment]
According to @gibbed

None = 0, // all platforms
BiowareZlib = 1, // all platforms
LZMA = 2, // PS3
XMemLZX = 3, // XBOX 360
HeaderlessZlib = 7, // all platforms

http://svn.gib.me/public/bioware/trunk/Gibbed.Bioware.FileFormats/EncapsulatedResourceFile.cs

**Comment by gibbed** [comment]
Thanks for the ping, you made me realize I hadn't removed the old repo for my Bioware code. That code has been migrated to GitHub:

[EncapsulatedResourceFile.cs#L384](https://github.com/gibbed/Gibbed.Bioware/blob/master/projects/Gibbed.Bioware.FileFormats/EncapsulatedResourceFile.cs#L384)

(I'll be removing the old repo when I have time, so I don't want to leave you hanging in that case)

**Comment by clone2727** [comment]
With the merge of #577 and #578, this should now be handled.
