### ISSUE TITLE
Suboptimal engine performance

### ISSUE THREAD

**Issue by seedhartha** [xoreos/xoreos#347]
Somehow framerate in KotOR have degraded since I last visited (could be just me). Here are some ideas on how the engine could be optimized:
1. Render rooms and static objects as a single VBO.
2. Occlusion and backface culling.
3. Replace immediate mode calls with VBO.
4. Shaders for skeletal animation.
5. Texture mipmaps.
6. LOD meshes.
7. Separate frame locks for the world and GUI (maybe take it even further).

Any thoughts?

**Comment by DrMcCoy** [comment]
Frankly, I don't want to completely redo the renderer, because @mirv-sillyfish is already rewriting it. Any big chances we're doing there now will only make more work for mirv, and will need to be redone then anyways.

So that's kind of a blocker, unfortunately

**Comment by DrMcCoy** [comment]
But maybe @mirv-sillyfish could use some help getting the renderer rewrite in a working and mergeable state? I don't know how well that can be coordinated, though

**Comment by seedhartha** [comment]
I actually experimented with mirv's branch already and got overwhelmed with all the changes :P It would be great to get an overview of what is going on there and what is missing.

**Comment by seedhartha** [comment]
I'm going to clone mirv's branch, thoroughly examine the changes, fix the commit history as necessary and update KotOR engines to use the new renderer. I estimate it to take about one month. Is that okay with you, @mirv-sillyfish? Seems a little bit unethical to me :D

**Comment by mirv-sillyfish** [comment]
Fine with me!
Actually most of KotOR works on my branch, but that render path is disabled until vertex shader animations can be done. It means loading animation data into a buffer object, or texture buffer object, and obviously using it all in the vertex shader. Then meshes can be shared amongst nodes instead of each node having a unique copy.

**Comment by seedhartha** [comment]
Okay, #381 provides good enough FPS boost (up to 2 times). I don't think there is much need for anything else but minor optimizations at this point.
