### ISSUE TITLE
NWN2: Storage of class level data for the Creature class

### ISSUE THREAD

**Issue by rjshae** [xoreos/xoreos#376]
I might be reading the code wrong, but here's my interpretation of an issue with the Creature class in NWN2:

Issue: The Creature::loadProperties function call for Creature.cpp is loading the skill ranks from a "SkillList" block in the character's .bic file. However, in NWN2, the PC GFF3 file is storing individual level information in a "LvlStatList" group. Hence there are multiple "SkillList" blocks. (They likely do this so characters can have negative levels dynamically applied in-game.) However, it looks like the Creature::loadProperties call is only grabbing the skills, feats, and other level information for the first level.

Proposal: I think each level's information should be stored in a private Level class that is attached via a std::map to the Creature class instance. The information can then be rolled up into summary data fields (like _ranks[]) for quick access. Implementing this might require some changes to calls in the GFF3 classes, such as the getField(name) function.

Might this also be true of NWN?

**Comment by Nostritius** [comment]
I remember that we had a similar case for the kotor creature class, where a creature could have multiple class levels for example when the player char becomes a jedi, the old class level is stored and the new one is added. I've never played nwn2 but from what you've told, it might be a solution to use, what is already written for the kotor creature class, and modify it to use it for the nwn2 creature class.

**Comment by rjshae** [comment]
Thanks, I'll take a look.

**Comment by rjshae** [comment]
It looks like the Kotor solution is just a vector of level/class combinations, so a bit like what I did for NWN2 feats. I'll have a look at revamping the NWN2 creature class so the level information can be stored and rolled back as needed.

**Comment by rjshae** [comment]
It turns out only PCs and full party companions need this level stat capability; other creatures just use the default method to load stats. I'm not clear what the game engine does with level drains for non-PCs, since feats, skills, class level-ups, and ability bonuses aren't linked to particular levels. Probably something simple.

**Comment by rjshae** [comment]
I've tried to address this.
