### ISSUE TITLE
Dragon Age: Origins does not start on Windows

### ISSUE THREAD

**Issue by seedhartha** [xoreos/xoreos#421]
The issue is caused by [this](https://github.com/xoreos/xoreos/blob/2f8b9a66e4e274b2735d46804b3e64b03bcc5e7e/src/aurora/resman.cpp#L276) line which behaves differently on Windows and Unix systems.

**Comment by DrMcCoy** [comment]
This *should* fix it, I think: https://github.com/xoreos/xoreos/tree/fixdaopaths . Can you check?

It's basically the easy way out, adding a FilePath function that always follows the POSIX rules and using that in ResourceManager::indexArchive(). I also added that behaviour to the Doxygen comment.

In the future, we might want to see if there's a better solution for this, maybe.

**Comment by seedhartha** [comment]
Yes, that did fix the issue.
