### ISSUE TITLE
JADE: Read access violation after the intro videos (experimental renderer)

### ISSUE THREAD

**Issue by seedhartha** [xoreos/xoreos#424]
Jade Empire now crashes with read access violation after the intro videos, when using the experimental renderer (launch with --rendernew=1). Exception is thrown at [this](https://github.com/xoreos/xoreos/blob/b68e3b8f3d1fd9e95bc4694243d82ec8bdb87a24/src/graphics/aurora/texturehandle.cpp#L88) line.

**Comment by DrMcCoy** [comment]
Fixed by #437 :)
