### ISSUE TITLE
NWN2: Script length in Functions::executeScript

### ISSUE THREAD

**Issue by rjshae** [xoreos/xoreos#429]
In the 'xoreos/src/engines/nwn2/script/functions_actions.cpp' file, the 'executeScript' call is truncating the script name to 16 characters. It states, "Max resource name length is 16, and ExecuteScript should truncate accordingly". However, there are a number of stock scripts used in the game engine where 16 characters is not sufficient to distinguish the script name. For example: "nx_s2_influence_dove" and "nx_s2_influence_okku". Is this a legacy of copying the code from another game? The usual name length limit in NWN2 is 32 characters, at least for texture files.

**Comment by DrMcCoy** [comment]
Oh, right, yes, that's a copy-paste mistake from NWN, where that held true.

**Comment by rjshae** [comment]
Okay, thanks. I'll put in a revision.
