### ISSUE TITLE
Non-random numbers using Visual C++ runtime

### ISSUE THREAD

**Issue by seedhartha** [xoreos/xoreos#449]
std::rand always returns the same sequence when compiling xoreos using Visual Studio. Apparently, this is because we call std::srand from the main thread and std::rand from the game thread.

**Comment by DrMcCoy** [comment]
Oh, I hadn't even thought that the seed might be thread-local, good catch. I guess we should add an std::srand() call into the gamethread constructor as well?

(Would it make sense, in the long term, to move from std::rand() to the stuff found in C++11's `<random>`? Or doesn't it really matter for our use-cases?)

**Comment by seedhartha** [comment]
I think random from C++11 is the way to go. rand/srand in multithreaded environment seems to have undefined behavior.

**Comment by DrMcCoy** [comment]
Okay, yeah, that's bad :P

I mean, we're probably fine, since we're not using std::rand() simultaneously in multiple threads at the same time. But still, yeah.
