### ISSUE TITLE
KOTOR: Static objects are not handled as part of camera collision detection

### ISSUE THREAD

**Issue by seedhartha** [xoreos/xoreos#470]
Only room walkmesh is. This is because I use findIntersection method from global Pathfinding and static objects are only handled by the LocalPathfinding.

@Supermanu, should I add static objects to global Pathfinding or somehow implement findIntersection in LocalPathfinding? Or maybe you could do it yourself?

**Comment by Supermanu** [comment]
If you are not in a hurry, I could do it. After a quick glance, I think it could be implemented with ObjectWalkmesh by attaching a bounding box to it (it just needs a findIntersection method in BoundingBox). And then to find the intersection in LocalPathfinding by checking first the objects and second the globalpathfinding.
