### ISSUE TITLE
BUILD: Linking failure using MinGW and CMake

### ISSUE THREAD

**Issue by seedhartha** [xoreos/xoreos#473]
Trying to build the engine using latest MSYS 2, MinGW-w64 and CMake on Windows 7 results in the linking failure. [Here](https://gist.github.com/seedhartha/968478ab690026cd9cc74cfa893be3ef) are the errors. There are no compilation errors and the engine builds just fine using autotools.

**Comment by DrMcCoy** [comment]
Can you build with "make VERBOSE=1", so that the whole compiler/link command lines are printed?

I don't get it. Somehow, stuff is missing there, and it makes no sense

**Comment by seedhartha** [comment]
Sure, [here](https://gist.github.com/seedhartha/41cb45732d57cc3a91b1bb2a018b91e0) is a verbose log.

**Comment by seedhartha** [comment]
Okay, yeah, changing the order or libraries in rules.mk fixes most of the errors.

**Comment by DrMcCoy** [comment]
Aaah, okay, that makes sense :)

**Comment by seedhartha** [comment]
Fixed.
