### ISSUE TITLE
KOTOR: Target selection projection bug

### ISSUE THREAD

**Issue by seedhartha** [xoreos/xoreos#480]
Currently, if you select an object and then start moving in the opposite direction, selection will appear on screen (the object is behind the camera).

**Comment by DrMcCoy** [comment]
Yes, you're capturing the object from the other side of the camera here. Or rather, from behind the near clipping plane.

You need to check the z value returned from the `project()` call. See https://github.com/xoreos/xoreos/blob/master/src/engines/nwn/gui/widgets/tooltip.cpp#L159 for comparison. If z is < 0, the object is behind the near clipping plane. If z is > 1, it's outside the far clipping plane.
