### ISSUE TITLE
NWN2: Dependencies for unit testing the Door class

### ISSUE THREAD

**Issue by rjshae** [xoreos/xoreos#497]
In the NWN2 Door class, instantiation via the "Door::Door(Module &module, const Aurora::GFF3Struct &door)" function requires passing a pointer to the module instance. This in turn adds a set of dependencies on the Console and NWN2Engine classes, &c.  Rather than attempting to generate these extra classes and run into a bunch of issues therein, I was thinking of just adding a "Module::Module()" initialization function to the Module class, which would be intended for use with the Door unit test (but could potentially be used for Area class testing as well). This would just leave the Module's _console variable as nullptr. However, (I think that) none of the module.cpp functions the unit test would run call a _console function. I can't see anybody creating a Module class instance this way than for unit testing.

Is this acceptable? Perhaps if I add some exception handling around the _console function calls in module.cpp?

**Comment by DrMcCoy** [comment]
Yeah, that's acceptable, as long as you add checks to make sure that nothing ever derefs that nullptr.

**Comment by rjshae** [comment]
Thank you. Hopefully I can get it to work.
