### ISSUE TITLE
Pathfinding issues in KotOR

### ISSUE THREAD

**Issue by seedhartha** [xoreos/xoreos#509]
In modules "manm26ab" and "korr_m36aa" in KotOR it is impossible to walk through the following areas:

![2019-03-24_07-52-56](https://user-images.githubusercontent.com/7695218/54873510-35c12280-4e0a-11e9-9593-5753ef4b865b.png)
![2019-03-24_07-54-15](https://user-images.githubusercontent.com/7695218/54873511-378ae600-4e0a-11e9-94d1-a06ae2d22812.png)

Also, when I tried using pathfinding (LocalPathfinding::findPathTo) in the starting area of KotOR (end_m01aa), the path was incorrectly calculated (it even crashed ocassionaly).

**Comment by Supermanu** [comment]
Thanks for reporting it, I'll have a look. LocalPathfinding::findPathTo still needs some adjustments, I wanted to test some ideas about performance improvement but I should focus to have something functional.
