### ISSUE TITLE
Star Wars: The Old Republic MMORPG

### ISSUE THREAD

**Issue by oxr463** [xoreos/xoreos#518]
Pardon my ignorance, but does SW:TOR run on a newer version of the KOTOR I & II engine? Similar to Fallout 3/NV and Fallout 4.

It would be awesome to see an emulator similar to Star Wars Galaxy.

**Comment by XJDHDR** [comment]
No, TOR uses the Hero engine whereas the KOTOR games (as well as almost all the other games Xoreos supports) use the Aurora engine.

**Comment by DrMcCoy** [comment]
Yeah, like @XJDHDR says, SW:TOR uses a different engine and is totally out of scope for xoreos.

**Comment by oxr463** [comment]
Oh I see. I'm a little bummed, but thanks for the info!
