### ISSUE TITLE
BUILD: Can't find SDL.h in VS2017

### ISSUE THREAD

**Issue by rickjs** [xoreos/xoreos#520]
While trying to compile in VS2017, I ran into this issue. I have the include directory for freetype, boost, etc for VC++ Include Directory in the Properties page pointed to a functions(boost, freetype,etc) include directory. The project finds boost, freetype, etc includes ok. But for the project file types.h in graphics directory, error at line 32, #include <SDL.h>(can't find), the file is in directory SDL, I have to change line 32 to  #include <SDL/SDL.h> for it to work. The line 32 doesn't seem to be right.

Rick

**Comment by DrMcCoy** [comment]
Well, no, the include is correct. It's just that the SDL directory should have been put into the include path...

Can anybody with Visual Studio knowledge check this, please? @seedhartha, @Nostritius, anybody else? :P

**Comment by rickjs** [comment]
That explains why when building cmake, the config never finds the SDL include. In the cmake gui config, I have to set it to the SDL2 directory for the SDL2_INCLUDE_DIR directory. There is no sdl.h in the include directory but is in include/SDL2. Or the SDL find is not working.

**Comment by Nostritius** [comment]
I assume you built your version of SDL2 by yourself and installed it or used a package manager like vcpkg? Because, as i realized by myself, sometimes they use the include/SDL2 directory structure and sometimes just the include directory. I think we should extend our finder script with this path suffix.

**Comment by rickjs** [comment]
SDL2 was installed by msys2/mingw64 pacman update, version 2.0.9-1. I have a side question, is there max versions for xoreos libraries? I had to rolled back Boost version, build complained about v1.69.

**Comment by DrMcCoy** [comment]
If that's just a case of extending/fixing our search script, that would be great. @Nostritius, can you do this, please? :)

>  is there max versions for xoreos libraries

There *shouldn't* be. Any compile error in new versions of libraries should be considered a bug.

There was something about Boost 1.69, @seedhartha talked about that, I think? But of course, I don't really remember right now, need to dig into my logs.

What version of xoreos are you compiling? A release, or a current git checkout? If the former, could you try the current git master branch, and see if we already fixed that?

If it's not fixed, please open a new bug for that, then, with the exact error you're getting. Thanks!

**Comment by Nostritius** [comment]
@rickjs Could you test if the path problem is solved with the changes made in #524?

**Comment by DrMcCoy** [comment]
Fixed with #524 :)
