### ISSUE TITLE
Not enabling XML causes errors in xml.cpp

### ISSUE THREAD

**Issue by rickjs** [xoreos/xoreos#523]
Only enabling NWN2 engine, looks like libxml is not needed. So undefined ENABLE_XML but have errors in xml.cpp, compiling in VS2017. Looks like you need a  ifdef  ENABLE_XML shell like in xml.h. Or is XML so embedded in the code, you can't disable XML anymore?

**Comment by rjshae** [comment]
libxml will be required for the GUI components of NWN2.

**Comment by DrMcCoy** [comment]
In the future, NWN2 will need libxml, yes. Currently, it doesn't yet, though.

What exactly did you do?
What did you expect to happen?
What did happen?
What were the exact error messages, if any?

**Comment by rickjs** [comment]
Hi,

Not an issue, just enabled XML.

Thanks,

Rick

________________________________

**Comment by DrMcCoy** [comment]
Okay, then I'm closing this issue :)
