### ISSUE TITLE
BUILD: Automake Travis does not fail if unit tests fail

### ISSUE THREAD

**Issue by Nostritius** [xoreos/xoreos#526]
I recognized in my #525 PR that the TRavis automake builds won't faile if the unit tests fail. It might be worth to fix this.

**Comment by DrMcCoy** [comment]
I think the problem is the `make -j4 check || cat test-suite.log`, this makes the fail not propagate.

Note to self: change this to `make -j4 check || (cat test-suite.log; exit 1)`, which should work.

**Comment by DrMcCoy** [comment]
7bc48cfe0c3eedc4097504eb36ee2224347df9cc should be it.

(@clone2727 rightfully complained that it doesn't propagate the original error code, though we probably won't need that. A different solution that does pass through the error code would be `make -j4 check; C=$?; test -e test-suite.log && cat test-suite.log; exit $C`.)
