### ISSUE TITLE
Feature: update GFF fields for DA2

### ISSUE THREAD

**Issue by dhk-room101** [xoreos/xoreos#555]
[DA2StringID2OGG.zip](https://github.com/xoreos/xoreos/files/4351978/DA2StringID2OGG.zip)

Add an alias attribute for fields 5231 and 5232 for gff2xml, e.g.
Plot GUID <string label="5231">49BEAD07708649F0AC61A9AF4FF03127</string>
Plot flag <uint16 label="5232">9</uint16>

These two fields are useful in conversation lines (.CL), for example, to populate with actors that match the plot and flag

Also I don't know if you care, but I attached a map of talk string IDs to their FNV32 sound file name equivalent in DA2. 

Thanks.

**Comment by DrMcCoy** [comment]
Ah, thanks! :)
