### ISSUE TITLE
KOTOR: Crash on New Game, hiding HUD parts

### ISSUE THREAD

**Issue by TimeFreeze1337** [xoreos/xoreos#557]
Sometimes xoreos will crash after confirming your character, the error in the Terminal is always: 

> Loading texture pack 2
> WARNING: Failed to create texture "mainmenu_a00005" (-1)
>     Because: No such image resource "mainmenu_a00005"
> Segmentation fault (core dumped)

after that when i try it again it will mostly load into the game.

I will also attach 2 Terminal Outputs one where it worked and the one crashed maybe there are also here and there a few helpful things to look at.
[Terminal Output Crash.txt](https://github.com/xoreos/xoreos/files/5021492/Terminal.Output.Crash.txt)
[Terminal Output Working.txt](https://github.com/xoreos/xoreos/files/5021493/Terminal.Output.Working.txt)

**Comment by DrMcCoy** [comment]
Hmm, the missing texture is not the problem the leads to the segfault there, I think.

Can you attach a debugger and get a stack trace out of it? Well, and compile xoreos yourself instead of using one of our binary packages, because those have their debug symbols stripped.

**Comment by TimeFreeze1337** [comment]
If you tell me how to attach a debugger and get a stack trace i can do it.

**Comment by DrMcCoy** [comment]
On Linux, you want to do

```
gdb --args ./xoreos -p /path/to/game
```

On the gdb prompt, type `run` to start xoreos. Once it crashes, type `bt` for a stack trace.

Keep in mind that when it crashes in a debugger, the game window will still be there but won't react to anything, so don't start it in fullscreen mode, otherwise you might inadvertently lock yourself out.

**Comment by TimeFreeze1337** [comment]
Okay here it is: 

`#0  0x000055555582c4e8 in Engines::KotORBase::HUD::hideTargetInformation (this=0x7fffb8099550)
    at src/engines/kotorbase/gui/hud.cpp:391
#1  0x000055555582c595 in Engines::KotORBase::HUD::hideSelection (this=<optimized out>)
    at src/engines/kotorbase/gui/hud.cpp:128
#2  0x000055555582c81c in Engines::KotORBase::IngameGUI::hideSelection (this=<optimized out>)
    at ./src/common/scopedptr.h:130
#3  0x0000555555830c87 in Engines::KotORBase::Module::unload (this=0x7fffb8c663c0, 
    completeUnload=<optimized out>) at ./src/common/scopedptr.h:130
#4  0x00005555558337ad in Engines::KotORBase::Module::loadModule (this=0x7fffb8c663c0, module=..., 
    entryLocation=..., entryLocationType=Engines::KotORBase::kObjectTypeInvalid)
    at src/engines/kotorbase/module.cpp:144
#5  0x0000555555758845 in Engines::KotOR::CharacterGenerationMenu::start (this=0x7fffb9d15160)
    at src/engines/kotor/gui/chargen/charactergeneration.cpp:243
#6  0x000055555575a4bc in Engines::KotOR::QuickCharPanel::callbackActive (this=0x7fffba6e02f0, 
    widget=...) at src/engines/kotor/gui/chargen/quickchar.cpp:76
#7  0x000055555585495c in Engines::GUI::checkWidgetActive (this=this@entry=0x7fffba6e02f0, 
    widget=<optimized out>) at src/engines/aurora/gui.cpp:495
#8  0x0000555555855178 in Engines::GUI::mouseUp (this=this@entry=0x7fffba6e02f0, event=...)
    at src/engines/aurora/gui.cpp:542
#9  0x000055555585551e in Engines::GUI::mouseUp (event=..., this=0x7fffba6e02f0)
    at src/engines/aurora/gui.cpp:529
#10 Engines::GUI::processEventQueue (this=0x7fffba6e02f0) at src/engines/aurora/gui.cpp:208
#11 0x0000555555855901 in Engines::GUI::run (this=0x7fffb9d15160, startCode=<optimized out>)
    at src/engines/aurora/gui.cpp:138
#12 0x0000555555855ba3 in Engines::GUI::sub (this=this@entry=0x7fffb9e899e0, gui=..., 
    startCode=startCode@entry=0, showSelf=showSelf@entry=true, hideSelf=hideSelf@entry=true)
    at src/engines/aurora/gui.cpp:377
#13 0x0000555555756b7b in Engines::KotOR::ClassSelectionMenu::callbackActive (this=0x7fffb9e899e0, 
    widget=...) at ./src/common/scopedptr.h:126
#14 0x000055555585495c in Engines::GUI::checkWidgetActive (this=this@entry=0x7fffb9e899e0, 
    widget=<optimized out>) at src/engines/aurora/gui.cpp:495
#15 0x0000555555855178 in Engines::GUI::mouseUp (this=this@entry=0x7fffb9e899e0, event=...)
    at src/engines/aurora/gui.cpp:542
#16 0x000055555585551e in Engines::GUI::mouseUp (event=..., this=0x7fffb9e899e0)
    at src/engines/aurora/gui.cpp:529
#17 Engines::GUI::processEventQueue (this=0x7fffb9e899e0) at src/engines/aurora/gui.cpp:208
#18 0x00005555558558e8 in Engines::GUI::run (this=0x7fffb9e899e0, startCode=<optimized out>)
    at src/engines/aurora/gui.cpp:136
#19 0x0000555555855ba3 in Engines::GUI::sub (this=this@entry=0x7fffe0ff8c50, gui=..., 
    startCode=startCode@entry=0, showSelf=showSelf@entry=true, hideSelf=hideSelf@entry=true)
    at src/engines/aurora/gui.cpp:377
#20 0x000055555574e167 in Engines::KotOR::MainMenu::callbackActive (this=0x7fffe0ff8c50, 
    widget=...) at ./src/common/scopedptr.h:126
#21 0x000055555585495c in Engines::GUI::checkWidgetActive (this=this@entry=0x7fffe0ff8c50, 
    widget=<optimized out>) at src/engines/aurora/gui.cpp:495
#22 0x0000555555855178 in Engines::GUI::mouseUp (this=this@entry=0x7fffe0ff8c50, event=...)
    at src/engines/aurora/gui.cpp:542
#23 0x000055555585551e in Engines::GUI::mouseUp (event=..., this=0x7fffe0ff8c50)
    at src/engines/aurora/gui.cpp:529
#24 Engines::GUI::processEventQueue (this=0x7fffe0ff8c50) at src/engines/aurora/gui.cpp:208
#25 0x00005555558558e8 in Engines::GUI::run (this=0x7fffe0ff8c50, startCode=<optimized out>)
    at src/engines/aurora/gui.cpp:136
#26 0x000055555574c250 in Engines::KotOR::Game::mainMenu (this=0x7fffb8c92ff0)
    at src/engines/kotor/game.cpp:113
#27 0x000055555574c3ec in Engines::KotOR::Game::run (this=0x7fffb8c92ff0)
    at src/engines/kotor/game.cpp:73
#28 0x000055555574a153 in Engines::KotOR::KotOREngine::run (this=0x7fffb8000b60)
    at /usr/include/c++/10.1.0/bits/unique_ptr.h:420
#29 0x0000555555813638 in Engines::GameInstanceEngine::run (this=0x55555611deb0)
    at ./src/common/scopedptr.h:130
#30 0x0000555555813b13 in Engines::EngineManager::run (this=0x55555611de90, game=...)
    at src/engines/enginemanager.cpp:252
#31 0x0000555555813ef5 in Engines::GameThread::threadMethod (this=0x555555e5d7e0)
    at ./src/common/scopedptr.h:126
#32 0x00005555558a628e in Common::Thread::threadHelper (obj=0x555555e5d7e0)
    at src/common/thread.cpp:108
#33 0x00007ffff5240b74 in std::execute_native_thread_routine (__p=0x55555611e5b0)
    at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:80
#34 0x00007ffff4ff7422 in start_thread () from /usr/lib/libpthread.so.0
#35 0x00007ffff4f26bf3 in clone () from /usr/lib/libc.so.6`

**Comment by DrMcCoy** [comment]
Just to make sure, that is a recent version of xoreos, right? 0.0.6, git commit 4f612dbdc487?

What does gdb say right when it crashes, before you type bt?

**Comment by TimeFreeze1337** [comment]
Yes its the recent version with the correct git commit yes. Freshly compiled today. 

It says: 

> Thread 14 "xoreos" received signal SIGSEGV, Segmentation fault.
> [Switching to Thread 0x7fffe0ff9700 (LWP 63433)]
> 0x000055555582c4e8 in Engines::KotORBase::HUD::hideTargetInformation (this=0x7fffbc099550)
>     at src/engines/kotorbase/gui/hud.cpp:391
> 391			_targetNameBackground->setInvisible(true);
>

**Comment by TimeFreeze1337** [comment]
I might be wrong but i think the output is slightly different this time so i just post it as well just to be safe: 

> #0  0x000055555582c4e8 in Engines::KotORBase::HUD::hideTargetInformation (this=0x7fffbc099550)
>     at src/engines/kotorbase/gui/hud.cpp:391
> #1  0x000055555582c595 in Engines::KotORBase::HUD::hideSelection (this=<optimized out>)
>     at src/engines/kotorbase/gui/hud.cpp:128
> #2  0x000055555582c81c in Engines::KotORBase::IngameGUI::hideSelection (this=<optimized out>)
>     at ./src/common/scopedptr.h:130
> #3  0x0000555555830c87 in Engines::KotORBase::Module::unload (this=0x7fffbcc693d0, 
>     completeUnload=<optimized out>) at ./src/common/scopedptr.h:130
> #4  0x00005555558337ad in Engines::KotORBase::Module::loadModule (this=0x7fffbcc693d0, module=..., 
>     entryLocation=..., entryLocationType=Engines::KotORBase::kObjectTypeInvalid)
>     at src/engines/kotorbase/module.cpp:144
> #5  0x0000555555758845 in Engines::KotOR::CharacterGenerationMenu::start (this=0x7fffbde6d760)
>     at src/engines/kotor/gui/chargen/charactergeneration.cpp:243
> #6  0x000055555575a4bc in Engines::KotOR::QuickCharPanel::callbackActive (this=0x7fffbe6e34f0, 
>     widget=...) at src/engines/kotor/gui/chargen/quickchar.cpp:76
> #7  0x000055555585495c in Engines::GUI::checkWidgetActive (this=this@entry=0x7fffbe6e34f0, 
>     widget=<optimized out>) at src/engines/aurora/gui.cpp:495
> #8  0x0000555555855178 in Engines::GUI::mouseUp (this=this@entry=0x7fffbe6e34f0, event=...)
>     at src/engines/aurora/gui.cpp:542
> #9  0x000055555585551e in Engines::GUI::mouseUp (event=..., this=0x7fffbe6e34f0)
>     at src/engines/aurora/gui.cpp:529
> #10 Engines::GUI::processEventQueue (this=0x7fffbe6e34f0) at src/engines/aurora/gui.cpp:208
> #11 0x0000555555855901 in Engines::GUI::run (this=0x7fffbde6d760, startCode=<optimized out>)
>     at src/engines/aurora/gui.cpp:138
> #12 0x0000555555855ba3 in Engines::GUI::sub (this=this@entry=0x7fffbde89880, gui=..., 
>     startCode=startCode@entry=0, showSelf=showSelf@entry=true, hideSelf=hideSelf@entry=true)
>     at src/engines/aurora/gui.cpp:377
> #13 0x0000555555756b7b in Engines::KotOR::ClassSelectionMenu::callbackActive (this=0x7fffbde89880, 
>     widget=...) at ./src/common/scopedptr.h:126
> #14 0x000055555585495c in Engines::GUI::checkWidgetActive (this=this@entry=0x7fffbde89880, 
>     widget=<optimized out>) at src/engines/aurora/gui.cpp:495
> #15 0x0000555555855178 in Engines::GUI::mouseUp (this=this@entry=0x7fffbde89880, event=...)
>     at src/engines/aurora/gui.cpp:542
> #16 0x000055555585551e in Engines::GUI::mouseUp (event=..., this=0x7fffbde89880)
>     at src/engines/aurora/gui.cpp:529
> #17 Engines::GUI::processEventQueue (this=0x7fffbde89880) at src/engines/aurora/gui.cpp:208
> #18 0x00005555558558e8 in Engines::GUI::run (this=0x7fffbde89880, startCode=<optimized out>)
>     at src/engines/aurora/gui.cpp:136
> #19 0x0000555555855ba3 in Engines::GUI::sub (this=this@entry=0x7fffe0ff8c50, gui=..., 
>     startCode=startCode@entry=0, showSelf=showSelf@entry=true, hideSelf=hideSelf@entry=true)
>     at src/engines/aurora/gui.cpp:377
> #20 0x000055555574e167 in Engines::KotOR::MainMenu::callbackActive (this=0x7fffe0ff8c50, 
>     widget=...) at ./src/common/scopedptr.h:126
> #21 0x000055555585495c in Engines::GUI::checkWidgetActive (this=this@entry=0x7fffe0ff8c50, 
>     widget=<optimized out>) at src/engines/aurora/gui.cpp:495
> #22 0x0000555555855178 in Engines::GUI::mouseUp (this=this@entry=0x7fffe0ff8c50, event=...)
>     at src/engines/aurora/gui.cpp:542
> #23 0x000055555585551e in Engines::GUI::mouseUp (event=..., this=0x7fffe0ff8c50)
>     at src/engines/aurora/gui.cpp:529
> #24 Engines::GUI::processEventQueue (this=0x7fffe0ff8c50) at src/engines/aurora/gui.cpp:208
> #25 0x00005555558558e8 in Engines::GUI::run (this=0x7fffe0ff8c50, startCode=<optimized out>)
>     at src/engines/aurora/gui.cpp:136
> #26 0x000055555574c250 in Engines::KotOR::Game::mainMenu (this=0x5555588785d0)
>     at src/engines/kotor/game.cpp:113
> #27 0x000055555574c3ec in Engines::KotOR::Game::run (this=0x5555588785d0)
>     at src/engines/kotor/game.cpp:73
> #28 0x000055555574a153 in Engines::KotOR::KotOREngine::run (this=0x7fffbc000b60)
>     at /usr/include/c++/10.1.0/bits/unique_ptr.h:420
> #29 0x0000555555813638 in Engines::GameInstanceEngine::run (this=0x555557687eb0)
>     at ./src/common/scopedptr.h:130
> #30 0x0000555555813b13 in Engines::EngineManager::run (this=0x555557687e90, game=...)
>     at src/engines/enginemanager.cpp:252
> #31 0x0000555555813ef5 in Engines::GameThread::threadMethod (this=0x555555e5d7e0)
>     at ./src/common/scopedptr.h:126
> #32 0x00005555558a628e in Common::Thread::threadHelper (obj=0x555555e5d7e0)
>     at src/common/thread.cpp:108
> #33 0x00007ffff5240b74 in std::execute_native_thread_routine (__p=0x555557690500)
>     at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:80
> #34 0x00007ffff4ff7422 in start_thread () from /usr/lib/libpthread.so.0
> #35 0x00007ffff4f26bf3 in clone () from /usr/lib/libc.so.6
>

**Comment by DrMcCoy** [comment]
```
print _targetNameBackground
```

I'm assuming it's not 0, because that caught by the check on line above. So that label does exist, it's just invalid memory for some reason, i.e. it was deleted between aquiring and trying to hide it.

Yeah, I'll have to spend some time investigating it, can't fix that right now on the quick. Thanks for reporting!

**Comment by TimeFreeze1337** [comment]
No problem. Always trying to help!

**Comment by DrMcCoy** [comment]
Hmm, I can't seem to be able to reproduce it here.

Can you give me the exact steps you take, including where you click, which character class and gender you choose, etc. pp. where it crashes for you?

**Comment by TimeFreeze1337** [comment]
Sure: 

Settings, gameplay, back , graphics, screen resolution switching to a higher resolution, back , advanced graphics , enable everything only exception is vsync which is still off. new game , male soldier , custom character clicking on a few things like portrait or attributes [where nothing happens btw] , clicking on back which also wont work , cancel , quick character , switching between a few portraits [doesnt matter which one you choose] , name and click a few times on generate then just hit start and it should crash.

**Comment by DrMcCoy** [comment]
Okay, this should be fixed now. Thanks for reporting! :)

The issue was related to the resolution change: this triggers a reloading of the UI (because KotOR has several different versions depending on the resolution), which then invalidates UI elements we've picked out for updating (like the name label for the current target). This is now fixed by re-grabbing those elements after the UI was reloaded.
