### ISSUE TITLE
JADE: Vertex layout

### ISSUE THREAD

**Issue by logzero** [xoreos/xoreos#81]
Wow, I had no idea that there is a PC version of this game. I did a quick apitrace run with the GOG version.

Most complex vertex declaration in the trace:
Stream = 0, Offset = 0, FLOAT3, POSITION
Stream = 0, Offset = 12, FLOAT3, NORMAL
Stream = 2, Offset = 0, FLOAT2, TEXCOORD
Stream = 3, Offset = 0, D3DCOLOR, COLOR
Stream = 3, Offset = 4, SHORT4N, TANGENT
Stream = 3, Offset = 12, SHORT4N, TANGENT
Stream = 3, Offset = 20, SHORT4N, TANGENT

Vertex streams:
StreamNumber = 0, pStreamData = 0x736e140, OffsetInBytes = 82728, Stride = 24
StreamNumber = 2, pStreamData = 0x736e200, OffsetInBytes = 27576, Stride = 8
StreamNumber = 3, pStreamData = 0x736e2c0, OffsetInBytes = 12768, Stride = 28

There are simpler variants without color and/or without tangent space(?). The most simple being position + texcoord in one stream, probably UI.

**Comment by DrMcCoy** [comment]
Oh, D3DCOLOR and SHORT4N, these are apparently the mysterious 4 byte and 8 byte fields I saw. :)

**Comment by DrMcCoy** [comment]
Oh, D3DCOLOR and SHORT4N, these are apparently the mysterious 4 byte and 8 byte fields I saw. :)

**Comment by DrMcCoy** [comment]
Okay, I moved this information into our wiki here: https://wiki.xoreos.org/index.php?title=Jade_Empire/Research#Vertex_layout :)

I can also give you an account for the wiki, if you want to add more stuff yourself.

Can you find out in what order these fields are? There should be one fixed order, even if not all might be present everywhere.

**Comment by logzero** [comment]
Yeah, I'll have a look a bit later today.

**Comment by logzero** [comment]
There will be some delays.

Have got master built and running, but getting:
ERROR: No such archive file "chitin.key"!

I vaguely remember this issue, but no idea what the fix was...

**Comment by DrMcCoy** [comment]
Errm, that's bad; that really shouldn't happen... :/

The file is there? The file permissions are okay?
If you could trace that issue, that would be great. Because that's kinda a catastrophic issue right there...

**Comment by DrMcCoy** [comment]
Hmm, or do you have the file and/or directory symlinked? Or a subpath of that?

**Comment by logzero** [comment]
Here is what I've got so far...

The block:

ctx.mdl->skip(8); // Unknown
uint32 offNormals = ctx.mdl->readUint32LE();
ctx.mdl->skip(4); // Unknown
uint32 offUV[4];
offUV[0] = ctx.mdl->readUint32LE();
offUV[1] = ctx.mdl->readUint32LE();
offUV[2] = ctx.mdl->readUint32LE();
offUV[3] = ctx.mdl->readUint32LE();
ctx.mdl->skip(20); // Unknown

is very probably:

ctx.mdl->skip(4); // Unknown
uint32 offAttribs[12] = ctx.mdl->readUint32LE(12);

The vertex attribute offsets offAttribs[12] look like this (as seen in players.mod):

0, 12, ~0, ~0, ~0, ~0, ~0, ~0, ~0, ~0, ~0, ~0
0, 12, ~0, 16, ~0, ~0, ~0, ~0, ~0, ~0, ~0, ~0
0, 12, ~0, 20, ~0, ~0, ~0, ~0, ~0, ~0, ~0, 16


Which suggests the following vertex layouts:

16 = 12 + 4 + 0 + 0
24 = 12 + 4 + 0 + 8
28 = 12 + 4 + 4 + 8
40 = 12 + 4 + 0 + 0 + 24
52 = 12 + 4 + 4 + 8 + 24

The first 12 bytes are the position.
Then we have two times 4 bytes that are unknown, color?
Those are followed by 8 bytes texcoords.
The 24 bytes are probably 3 tangent space vecs. They are not in the offsets array, probably not supported by mdl file format as such.

The second 4 byte block is often 0 0 0 0

The "tangent space" block doesn't look like normalized vecs though, not sure what is going on there:
values 0-3 look ok
values 4-7 are often all zero???
values 8-11 are often close to zero

I think it will require a closer look at the shaders, to see what the are doing with those attributes.

**Comment by DrMcCoy** [comment]
Hmm, very interesting, thanks! :)

**Comment by logzero** [comment]
The second attribute (at offset 12) is not a color
http://i.imgur.com/iBGGwbW.jpg

**Comment by DrMcCoy** [comment]
Huh, okay. Well, I have no clue what it could be, at this point.

Thanks looking into this, though :)

**Comment by logzero** [comment]
I hope it is ok, if I keep spamming this issue :) 

Assuming two 16bit values (ushort) we get this:
http://i.imgur.com/TQzYDmy.jpg
http://i.imgur.com/R3AmvAC.jpg
http://i.imgur.com/C0zX4oG.jpg
http://i.imgur.com/e9wrarD.jpg

And with a 32 bit value (uint):
http://i.imgur.com/GKMVu1z.jpg
http://i.imgur.com/Xnj5tYU.jpg
http://i.imgur.com/tkNBBIa.jpg

Looks like some kind of shading parameter (luminance factor / baked lighting)?

**Comment by DrMcCoy** [comment]
> I hope it is ok, if I keep spamming this issue :) 

Very much so, thanks! While I'm currently focusing on something else, this is extremely useful for the future. :)

> Looks like some kind of shading parameter

Hmm, possible, yes.

**Comment by logzero** [comment]
The "last attribute" at offset 16 has often the value (4 bytes decimal): 0 0 128 63
Or 1.0 if interpreted as a float. The value is always <= 1.0 from what I've seen so far.

**Comment by logzero** [comment]
Here is how it looks like:
http://i.imgur.com/ecSFcAI.jpg
http://i.imgur.com/6bAYn3f.jpg

Looks like another shading / material parameter.
